spring:
  cloud:
    gateway:
      routes:
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - StripPrefix=0

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0